name: Spring Boot CI with Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker Image
      run: |
          cd ./actions
          docker build -t actions .

    # Optional: Run tests within the Docker container
    - name: Run Tests in Docker
      run: docker run --rm actions mvn test
